//! Debug inspection traits for interactive debugging of emulated machines.
//!
//! Three layers:
//! - `Debuggable` — any device that can present its register state
//! - `DebugCpu` — CPU-specific capabilities (extends Debuggable)
//! - `BusDebug` — bus-level discovery of all devices and CPUs

use crate::cpu::disasm::DisassembledInstruction;

/// A single CPU register for display in the debug panel.
pub struct DebugRegister {
    /// Register name (e.g., "A", "PC", "SP").
    pub name: &'static str,
    /// Register value (all register widths fit in u64).
    pub value: u64,
    /// Display width in bits (8 or 16).
    pub width: u8,
}

/// Result of disassembling one instruction at a given address.
pub struct DebugDisassembly {
    /// Address of the instruction.
    pub addr: u16,
    /// Raw instruction bytes.
    pub bytes: Vec<u8>,
    /// Formatted instruction text (e.g., "LDA  #$42").
    pub text: String,
    /// Total byte length of the instruction.
    pub byte_len: u8,
}

/// Any hardware device that can present its state for debug inspection.
///
/// Implemented by CPUs, PIAs, blitters, DACs, and other peripherals.
/// The debugger uses this to display device register panels.
pub trait Debuggable {
    /// Get all registers for display.
    fn debug_registers(&self) -> Vec<DebugRegister>;
}

/// CPU-specific debug capabilities (extends Debuggable).
///
/// Provides program counter access, instruction boundary detection,
/// and disassembly. The debugger uses this for stepping and code display.
pub trait DebugCpu: Debuggable {
    /// Read the current program counter.
    fn debug_pc(&self) -> u16;

    /// True if the CPU is at an instruction boundary (ready to fetch next opcode).
    fn debug_at_instruction_boundary(&self) -> bool;

    /// Disassemble one instruction from raw bytes at the given address.
    fn debug_disassemble(&self, addr: u16, bytes: &[u8]) -> DisassembledInstruction;
}

/// Debug view of a bus and its connected devices.
///
/// The debugger interrogates the bus to discover CPUs and peripherals.
/// Generated by `#[derive(BusDebug)]` on board/system structs.
pub trait BusDebug {
    /// All devices connected to this bus, with contextual names.
    /// CPUs appear here too (they implement Debuggable).
    fn devices(&self) -> Vec<(&str, &dyn Debuggable)>;

    /// CPUs on this bus (for stepping and disassembly).
    fn cpus(&self) -> Vec<(&str, &dyn DebugCpu)>;

    /// Side-effect-free memory read from a CPU's address space.
    /// Returns `None` for unmapped or I/O addresses.
    fn read(&self, cpu_index: usize, addr: u16) -> Option<u8>;

    /// Debug memory write into a CPU's address space.
    fn write(&mut self, cpu_index: usize, addr: u16, data: u8);

    /// Write to a device register by device index and register offset.
    /// Device indices match the order returned by `devices()`.
    /// Only `#[debug_device]` fields respond; CPU indices are ignored.
    fn write_device_register(&mut self, _device_index: usize, _offset: u8, _data: u8) {}

    /// Reset an individual device by index.
    /// Device indices match the order returned by `devices()`.
    fn reset_device(&mut self, _device_index: usize) {}
}
